# Site
repository: oneyanshi/oneyanshi.github.io
favicon: images/favicon.ico

# Personal info
name: Yan Shi
title: Data Engineer & Analyst 
email: itsyanshi@gmail.com
website: https://oneyanshi.github.io/

# Social links
# twitter_username: facespics
github_username:  oneyanshi 
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: oneyanshi
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Howdy! My name is Yan Shi. I'm searching for new opportunities that allow me to leaverage my data engineering and analytics skills. I'm interested in progressive spaces, and in places where communication and technology intersect. 

I code primarily in <mark>Python</mark>, but I'm also experienced in <mark>HTML</mark>, <mark>CSS</mark>, and vanilla <mark>JavaScript</mark>. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
